### ISSUE TITLE
Some code confusion

### ISSUE THREAD

**Issue by 1033020837** [YujiaBao/Distributional-Signatures#10]
I'm confused about the line 203 of meta.py:
w_target = torch.abs(ebd @ data['w_target'])
Why need to calculate absolute value here?

**Comment by YujiaBao** [comment]
Hi,

**Comment by YujiaBao** [comment]
Hi

**Comment by YujiaBao** [comment]
On line 203, we first compute the dot product of each category's weight vector and the word embedding. The reason why we take an absolute value is that here we care about the influence of the current word to the prediction:
1. If the outcome is a large positive number, this word is a very important feature.
2. If the outcome is a large negative number, then the current word should also be a strong indicator for this example not belonging to this category.

Anyway, these are some heuristics that we found pretty effective. Please feel free to make adjustments to fit your need.
