### ISSUE TITLE
Limited by my ability, some confusion about _meta_update function

### ISSUE THREAD

**Issue by hquzhuguofeng** [YujiaBao/Distributional-Signatures#19]
谢谢作者的代码分享哈：
       我目前还在学习中，您的maml.py下有个函数我看不明白：那就是_meta_update函数。
       以下是我的理解，不知道对不对，还望您的更正：
       我使用的是Bert作为embedding
       `        for _ in train_episodes:
            # update the initialization based on a batch of tasks
            total_grad = {'ebd': [], 'clf': []}

            for _ in range(args.maml_batchsize):
                # print('start', flush=True)
                task = next(sampled_tasks)

                # clone the current initialization
                _copy_weights(model['ebd'], fast_model['ebd'])
                _copy_weights(model['clf'], fast_model['clf'])

                # get the meta gradient
                if args.maml_firstorder:
                    train_one_fomaml(task, fast_model, args, total_grad)
                else:
                    train_one(task, fast_model, args, total_grad)
            # model是之前没有进行fintune的模型， total_grad是模型在finetune过程中记录的每一个轮次有gradient的参数的权重，opt是adam，task是输入的数据
            ebd_grad, clf_grad = _meta_update(
                    model, total_grad, opt, task, args.maml_batchsize,
                    args.clip_grad)
            meta_grad_dict['ebd'].append(ebd_grad)
            meta_grad_dict['clf'].append(clf_grad)`
           code from maml.py line 134-156
           一上来就是将Bert的权重复制到 fast_model，fast_model 就相当于Bert模型了。
           然后进入train_one_fomal函数，在support dataset上更新多轮参数，在query上更新一轮参数，此时更新的还是fast_model的参数，不过最后使用total_grad将所有含梯度的参数传递出来。
           关键是_meta_update这个函数：一上来就是用原来的model进行推理。avg_grad和hooks这两个地方我能力有限哈，实在看不明白啥意思，我大概的理解就是：选取total_grad的所有参数，这里面的参数求一个和，得到avg_grad,然后，因为求和了，所以要除以轮次？
           后面就是梯度的norm, 反向传播。我理解对吗大佬？

**Comment by YujiaBao** [comment]
”然后进入train_one_fomal函数，在support dataset上更新多轮参数，在query上更新一轮参数“: 在support data上更新多轮参数没错，在query上我们只通过现在更新好的参数evaluate一下loss，然后把这个loss的grad存到total_grad里。

"_meta_update" 这个函数主要是average一下所有episode的gradient（同时做一下gradient clipping），然后update所有的parameter。
