### ISSUE TITLE
How to use the bert pre-trained model on text classification

### ISSUE THREAD

**Issue by xuetrdi** [YujiaBao/Distributional-Signatures#2]
About how to use the bert pre-trained model in this project on text classification, i don't understand.
Should I do the following steps?
bert==True
snapshot=/path/to/pytorch-bert-pre-trained-model.ebd

**Comment by YujiaBao** [comment]
Here is an example of using CNN+prototypical network on top of Bert embeddings:python src/main.py --cuda=1 --shot=5 --way=5 --embedding=meta --classifier=r2d2 --mode=train --dataset=huffpost --data_path=data/huffpost_bert_uncase.json --
n_train_class 20 --n_val_class 5 --n_test_class 16 --meta_w_target --meta_idf --bert_path=/data/rsg/nlp/yujia/.pytorch_pretrained_bert --bert

**Comment by YujiaBao** [comment]
Snapshot is for loading pertrained model, not BERT. Here is an example of using AVG + prototypical network with BERT embedding on huffpost:
python src/main.py --cuda=1 --shot=5 --way=5 --embedding=avg --classifier=proto --mode=train --dataset=huffpost --data_path=data/huffpost_bert_uncase.json --
n_train_class 20 --n_val_class 5 --n_test_class 16 --meta_w_target --meta_idf --bert_path=/data/rsg/nlp/yujia/.pytorch_pretrained_bert --bert
