### ISSUE TITLE
Run Issue

### ISSUE THREAD

**Issue by AndrewSDennisRepo** [YujiaBao/Distributional-Signatures#20]
Hello, I have been trying to run your code and have gotten it to run but it gets to 

`Training on train:   0%\|                                \| 0/100 [00:00`

And never makes any progress. I am running this on my desktop which is large and GPU is enabled. Not sure if there is something wrong or what I need to do. I am using our.sh to run it. Any advice would be greatly appreciated.

**Comment by YujiaBao** [comment]
Hi Andrew, what's the system of your desktop? We've only tested our code on Ubuntu 14.04. If your OS is different, you may want to try virtual machine.

**Comment by AndrewSDennisRepo** [comment]
Yes, I will try out a VM
