### ISSUE TITLE
After training?

### ISSUE THREAD

**Issue by versipellis** [YujiaBao/Distributional-Signatures#24]
Maybe it's not super clear to me, but after you train and save the model, how do you use it?

**Comment by YujiaBao** [comment]
In line 294 of `src/main.py`, we evaluate the model on the testing data.

**Comment by versipellis** [comment]
Thanks. Can you not use it afterwards as a classifier on unlabeled data?

**Comment by rmwu** [comment]
You can directly return `pred` from line 70 of r2d2.py (or similar output variables in other classifiers) to obtain the model's output, pre-evaluation.

**Comment by versipellis** [comment]
thank you!
