### ISSUE TITLE
All vectors must have the same number of dimensions.

### ISSUE THREAD

**Issue by DC-gao** [YujiaBao/Distributional-Signatures#25]
File "D:\Users\Administrator\Anaconda3\lib\site-packages\torchtext\vocab.py", line 409, in cache
    dim))
RuntimeError: Vector for token b'iratapina' has 46 dimensions, but previously read vectors have 300 dimensions. All vectors must have the same number of dimensions.

**Comment by YujiaBao** [comment]
As suggested by the error massage, I think there is an issue with your downloaded word vectors. Please check it and make sure that all vectors have dimension 300.

**Comment by zhangjiawei1** [comment]
这个问题解决了吗
