### ISSUE TITLE
Some Errors and Requests

### ISSUE THREAD

**Issue by DC-gao** [YujiaBao/Distributional-Signatures#26]
Hello, dear author, when I set the CPU core to 10 according to your default, several errors occurred in the program.
     The first is that there is a parameter of self.num_cores in parallel_sampler.py, but it will report an error on line 135: AttributeError:'ParallelSampler' object has no attribute'num_cores'.
      Then, when calling ForkingPickler(file, protocol).dump(obj) of reduction.py, TypeError: can't pickle weakref objects appeared again.
      self = reduction.pickle.load(from_parent)
      EOFError: Ran out of input.
      
      I am a beginner in deep learning, maybe these problems are very low-level in your opinion, and I may still encounter some errors in subsequent runs. Therefore, I hope you can update more related code operations in your original mud, such as introducing the call flow of the entire program, which will provide great help to those of us with poor basics.
       In addition, in other people's questions, I have seen you say that your team is testing a project on the ubuntu system. If I want to run the project on Google Colaboratory, what adjustments need to be made.
      Finally, thank you very much for taking time out of your busy schedule to reply to my previous questions!

**Comment by YujiaBao** [comment]
Hi, our code is tested on Ubuntu. I am not very sure about Google Colab.

For the previous error, could you provide your python version and pytorch version?

**Comment by DC-gao** [comment]
Python3.7
Pytorch1.8.1

**Comment by DC-gao** [comment]
> 您好，我们的代码已在 Ubuntu 上进行了测试。我对 Google Colab 不太确定。
> 
> 对于之前的错误，你能提供你的python版本和pytorch版本吗？

**Comment by DC-gao** [comment]
> Hi, our code is tested on Ubuntu. I am not very sure about Google Colab.
> 
> For the previous error, could you provide your python version and pytorch version?

Thank you very much for your reply. When I use the Colaboratory of Google, there will be no such report error. Now the problem has been solved.
