### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by Recluse-0532** [YujiaBao/Distributional-Signatures#28]
你好，请问运行main.py后，服务器报错RuntimeError: Vector for token b'ophthalmology' has 219 dimensions, but previously read vectors have 300 dimensions. All vectors must have the same number of dimensions.
Killed怎么解决呢？
![111](https://user-images.githubusercontent.com/73507979/132457068-435741cd-29d4-4a0a-83b1-eaac33a6b853.png)

**Comment by YujiaBao** [comment]
It seems like your pretrained embeddings are broken. You may want to download it directly from https://dl.fbaipublicfiles.com/fasttext/vectors-wiki/wiki.en.vec
