### ISSUE TITLE
Questions about amazon view dataset setting

### ISSUE THREAD

**Issue by YueyuanKang** [YujiaBao/Distributional-Signatures#31]
Hi Yujia,
would you please tell me the setting of parameters in args
![image](https://user-images.githubusercontent.com/77316342/142370605-a7da2e3d-58fb-4507-a7c9-42b6fc58a828.png)

Thanks a lot!

Yueyuan

**Comment by YueyuanKang** [comment]
this is in the main.py. Thanks

**Comment by YujiaBao** [comment]
Hi! You can just comment out the corresponding lines in bin/our.sh.

```
dataset=amazon
data_path="data/amazon.json"
n_train_class=10
n_val_class=5
n_test_class=9
```

**Comment by YueyuanKang** [comment]
@YujiaBao 
I have used this setting and the setting below, This is also in our.sh
![image](https://user-images.githubusercontent.com/77316342/142468150-b2a7923e-ed8c-4d5a-ae1d-a6d2a6637f0d.png)

 but it came out of the warning below
![image](https://user-images.githubusercontent.com/77316342/142468446-8b5823b2-d5db-4b98-94e9-ab86162ae202.png)
 
Therefore, I want to double-check it. Do I need to use this part or I can only use the default setting?

Thank you.
