### ISSUE TITLE
Assigning 'CLS' when args.bert is True

### ISSUE THREAD

**Issue by pvij** [YujiaBao/Distributional-Signatures#4]
Thank you for open sourcing the code for your paper. I have one question. Shouldn't the line https://github.com/YujiaBao/Distributional-Signatures/blob/b014c354d636f637237ddc19d1c69c2d03c1e1c5/src/dataset/loader.py#L310 be `bert_id[:, 0] = tokenizer.convert_tokens_to_ids(['[CLS]'])[0]`? So that the first column is all 'CLS' rather than the first row?

Please correct me if I am wrong.

**Comment by YujiaBao** [comment]
Hi pvij, I think you are right.

**Comment by YujiaBao** [comment]
Hi pvij, I think you are right here: the special token of the first column is not correctly set.

Actually, we use a newer implementation (linked at our open review submission) for the iclr version. This implementation moves the Bert computation from data/ to embedding/cxtebd.py. And it does not have this problem.
https://github.com/distributionalsignatures/460d60d2c25a118c67dcbfdd37f27d6c

We will migrate the two versions soon.
