### ISSUE TITLE
The function _subset_selection in src/dataset/stats.py is never called

### ISSUE THREAD

**Issue by pvij** [YujiaBao/Distributional-Signatures#5]
As per the [paper](https://arxiv.org/abs/1908.06039), the source pool during meta training is all of training data except the data in training classes used for the episode and all of training data during meta testing. But the code doesn't seem to do this. Even during meta training, I think the source pool is constructed from the entire training set. I think the function `_subset_selection` has a role to play here but this function isn't called anywhere. If I am wrong, can you point the part of code that does the source pool construction during meta training as I am not able to find it?

**Comment by YujiaBao** [comment]
Hi pvij, thanks for checking out. _compute_idf and _compute_iwf return the statistics over the source pool. Both methods look at classes in the argument `classes`, aggregate their statistics, and return the idf and iwf (inverse word frequency).

**Comment by pvij** [comment]
You are right. I am wrong. Thanks for pointing it out.

**Comment by YujiaBao** [comment]
You are welcome!
