### ISSUE TITLE
One error when run ./bin/our.sh

### ISSUE THREAD

**Issue by zjcanjux** [YujiaBao/Distributional-Signatures#6]
RuntimeError: Vector for token b'kbh' has 161 dimensions, but previously read vectors have 300 dimensions. All vectors must have the same number of dimensions.
If you have time to response this issue, it will be helpful for me.

**Comment by glare-ni** [comment]
Hello, I ran into almost the same problem. Any advice would be greatly appreciated if you have time.

**Comment by YujiaBao** [comment]
> Hello, I ran into almost the same problem. Any advice would be greatly appreciated if you have time.

I guess there may be some issue with your downloaded word vectors. You can try to download it directly from "https://dl.fbaipublicfiles.com/fasttext/vectors-wiki/wiki.en.vec" and save it under `./`.
