### ISSUE TITLE
  Questions about training from the support set

### ISSUE THREAD

**Issue by liuLannister** [YujiaBao/Distributional-Signatures#7]
Hi, Why Formula 5 is not mentioned in regular.py? Don't we need to optimize the model parameters W based on the regularized squared loss before inferencing on the query set?

**Comment by YujiaBao** [comment]
Hi, Eq 5 is learning the base classifier (ridge regression in this case) on the support set. Since different base classifiers exhibit different training routines, we don't include them in regular.py. You can find Eq 5 in line 28 of '/src/classifier/r2d2.py'.
