### ISSUE TITLE
This line seems to be redundant

### ISSUE THREAD

**Issue by GeneZC** [YujiaBao/Distributional-Signatures#9]
https://github.com/YujiaBao/Distributional-Signatures/blob/e04970ff6399d34d439bc128fdd5b66d0eb49592/src/classifier/base.py#L81

An example from pytorch doc:
>>> output, inverse_indices = torch.unique(
        torch.tensor([1, 3, 2, 3], dtype=torch.long), sorted=True, return_inverse=True)
>>> output
tensor([ 1,  2,  3])
>>> inverse_indices
tensor([ 0,  2,  1,  2])

**Comment by YujiaBao** [comment]
Thank you for pointing that out.
